[package]
name = "shared"
version = "2.7.3"
edition = "2024"

[lib]
path = "src/lib.rs"

[profile.release]
opt-level = 3
debug = "none"
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1

[dependencies]
argon2 = "0.5.3"
blake3 = "1.8.5"
chacha20poly1305 = "0.10.1"
hex = "0.4.3"
ignore = "0.4.25"
num_cpus = "1.17.0"
rand = "0.8.6"
rayon = "1.12.0"
zeroize = "1.8.2"

[dependencies.x25519-dalek]
version = "2.0.1"
features = ["static_secrets"]

[dependencies.pqc_kyber]
version = "0.7.1"
features = ["kyber1024", "std"]
